name: Say hello 

on:
  push:
    branches:
      - main

jobs:
  hello_word:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: |
          echo "hola midu!"
      - name: Dime la fecha
        run: date
      - run: ls -l